description: |-
  This is something

  Wee
annotations:
  charts.openshift.io/name: Drupal
  charts.openshift.io/provider: CSDS
  charts.openshift.io/providerType: custom
apiVersion: v2
appVersion: 0.0.3
name: drupal
tags: php,drupal
sources:
  - https://github.com/something/chart
version: 0.0.1
