namespace: drupal
volume_capacity: 1Gi
site_name: app
config:
  port: 8080
  cim_update: false

image:
  repository: nginx
  pullPolicy: Always
  tag: "latest"

resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

