site_name: app
storage_size: 1Gi
storage_class: nfs-client
# openshift onprem nfs-rwx

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

cronjob:
  suspend: true
  schedule: '*/30 * * * *'
  token: 'abc123'
  image: registry.access.redhat.com/ubi9/ubi:latest

database:
  database: db
  host: dbhost
  username: dbuser
  password: dbpassword

pdb:
  minAvailable: 1

deployment:
  replicaCount: 1
  revisionHistoryLimit: 2
  port: 80
  env:
    php_memory: 768M
    display_errors: ON
    config_env: nonprod

service:
  type: ClusterIP
  port: 80

image:
  repository: nginx
  pullPolicy: Always
  tag: "latest"

resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /
    port: 80
    scheme: HTTP
  initialDelaySeconds: 30
  timeoutSeconds: 2
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /
    port: 80
    scheme: HTTP
  initialDelaySeconds: 20
  timeoutSeconds: 2
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3
