apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Values.site_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Values.site_name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: {{ .Values.site_name }}
    spec:
      containers:
      - env:
        - name: DRUPAL_CIM_UPDATE
          value: '{{ .Values.config.cim_update }}'
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - /usr/libexec/check-container
            - --live
          initialDelaySeconds: 120
          timeoutSeconds: 10
        name: {{ .Values.site_name }}
        ports:
        - containerPort: {{ .Values.config.port }}
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
#        volumeMounts:
#        - mountPath: /var/lib/pgsql/data
#          name: {{ .Values.database_service_name }}-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
#      volumes:
#      - name: {{ .Values.database_service_name }}-data
#        persistentVolumeClaim:
#          claimName: {{ .Values.database_service_name }}
status: {}