apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Values.site_name }}-updb"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ .Values.site_name }}-updb
    spec:
      restartPolicy: Never
      containers:
      - name:  {{ .Values.site_name }}-updb
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        envFrom:
        - secretRef:
            name: {{ .Values.site_name }}-mysqldb
        command: [{{ .Values.post_task.command |quote }}
