apiVersion: batch/v1
kind: Job
metadata:
  name: " {{ .Values.site_name }}-updb"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ .Values.site_name }}updb
    spec:
      restartPolicy: Never
      containers:
      - name:  "{{ .Values.site_name }}-updb"
        image: "alpine:3.3"
        command: ["/bin/sleep","{{ default "10" .Values.sleepyTime }}"]