kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: drupal-nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage_size }}
  storageClassName: {{ .Values.storage_class }}
  volumeMode: Filesystem

