kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.site_name }}-mysqldb
data:
  DRUPAL_DATABASE: {{ .Values.database.database }}
  DRUPAL_DATABASE_HOST: {{ .Values.database.host }}
  DRUPAL_DATABASE_PASSWORD: {{ .Values.database.password }}
  DRUPAL_DATABASE_USER: {{ .Values.database.user }}
type: Opaque
