apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.site_name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.port }}
      protocol: TCP
      name: {{ .Values.service.port }}-tcp
  selector:
    app: {{ .Values.site_name }}
